version: '3.8'

services:
  paypal-webhook2:
    image: python:3.10
    restart: always
    ports:
      - "8084:8000"
    container_name: paypal-webhook2
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && gunicorn -w 2 -b 0.0.0.0:8000 webhook:app"
    networks:
      - wikinet2

networks:
  wikinet2:
    external: true
