services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./wikijs.conf:/etc/nginx/conf.d/wikijs.conf
    restart: always
    network_mode: host
