services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./wikijs.conf:/etc/nginx/conf.d/wikijs.conf
    network_mode: host
    networks:
      - wikinet1
      - wikinet2
      - wikinet3
networks:
  wikinet1:
    external: true
  wikinet2:
    external: true
  wikinet3:
    external: true
