services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Redirige les requêtes HTTP vers le conteneur Nginx
    volumes:
      - ./nginx/wikijs.conf:/etc/nginx/conf.d/default.conf


