---
- name: Déploiement complet Wiki.js multisite avec Nginx et Docker (sans Certbot)
  hosts: wikijs_servers          # <-- corrige ici
  become: yes

  vars:
    repo_url: "https://github.com/Hanane-Chaouche/wikijs-multisite.git"
    repo_dest: "/opt/wikijs-deploy"
    docker_networks:
      - wikinet1
      - wikinet2
      - wikinet3

  tasks:
    - name: Installer les dépendances système
      apt:
        name:
          - apt-transport-https        # optionnel sur Ubuntu récents
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present

    - name: Installer Docker et Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Assurer que le service Docker est démarré
      service:
        name: docker
        state: started
        enabled: true

    - name: Cloner ou mettre à jour le dépôt du projet
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main
        force: no            # <-- évite l'écrasement
        update: yes

    - name: Créer les réseaux Docker (idempotent best-effort)
      shell: "docker network create {{ item }} || true"
      loop: "{{ docker_networks }}"

    - name: Lancer Wiki.js - wiki1
      shell: "docker compose -f {{ repo_dest }}/instances/wiki1/docker-compose.yml up -d"
      args:
        chdir: "{{ repo_dest }}/instances/wiki1"

    - name: Lancer Wiki.js - wiki2
      shell: "docker compose -f {{ repo_dest }}/instances/wiki2/docker-compose.yml up -d"
      args:
        chdir: "{{ repo_dest }}/instances/wiki2"

    - name: Lancer Wiki.js - wiki-public
      shell: "docker compose -f {{ repo_dest }}/instances/wiki-public/docker-compose.yml up -d"
      args:
        chdir: "{{ repo_dest }}/instances/wiki-public"

    - name: Lancer Nginx (reverse proxy)
      shell: "docker compose -f {{ repo_dest }}/nginx/docker-compose.yml up -d"
      args:
        chdir: "{{ repo_dest }}/nginx"

    - name: Lancer PayPal Webhook
      shell: "docker compose -f {{ repo_dest }}/paypal-webhook/docker-compose.yml up -d"
      args:
        chdir: "{{ repo_dest }}/paypal-webhook"

  handlers:
    - name: Reload Nginx
      shell: docker exec nginx nginx -s reload
      ignore_errors: yes     # <-- corrige ici
